version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      tooling:
        patterns: ["*"]
        exclude-patterns: ["@latkit/*"]
    open-pull-requests-limit: 3
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
    groups:
      ruby:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
